redis:
  hostname: redis
  domainname: localdomain
  image: redis

fountain:
  image: smartdeveloperhub/agora-fountain
  hostname: fountain
  domainname: localdomain
  links:
    - redis:redis
  command: /sbin/my_init
  environment:
    - TERM=xterm
    - AGORA_FOUNTAIN_VERSION=0.4.0.dev5
    - FOUNTAIN_CONFIG=agora.fountain.server.config.ProductionConfig

planner:
  image: smartdeveloperhub/agora-planner
  hostname: planner
  domainname: localdomain
  links:
    - fountain:fountain
    - redis:redis
  command: /sbin/my_init
  environment:
    - TERM=xterm
    - AGORA_PLANNER_VERSION=0.3.0.dev0
    - PLANNER_CONFIG=agora.planner.server.config.ProductionConfig

nginx:
  build: nginx
  hostname: nginx
  domainname: localdomain
  links:
    - planner:planner
    - fountain:fountain
  ports:
    - "9002:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf



