redis:
  hostname: redis
  domainname: localdomain
  build: redis

fountain:
  build: fountain
  hostname: fountain
  domainname: localdomain
  links:
    - redis:redis
  command: /sbin/my_init

planner:
  build: planner
  hostname: planner
  domainname: localdomain
  links:
    - fountain:fountain
    - redis:redis
  command: /sbin/my_init

nginx:
  build: nginx
  hostname: nginx
  domainname: localdomain
  links:
    - planner:planner
    - fountain:fountain
  ports:
    - "9002:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf



